### ISSUE TITLE
make sure whitespace is removed when adding PubMed IDs to the BioPax

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#105]
Code may be fixed already; I'll check that first.

**Comment by egonw** [comment]
Confirmed to not be fixed.

**Comment by DeniseSl22** [comment]
COuld be done with a simple string.trim() right?

**Comment by DeniseSl22** [comment]
See https://github.com/PathVisio/pathvisio/pull/112

**Comment by markwoon** [comment]
`String.trim()` only trims spaces.  Might want to be more careful and catch all whitespace (e.g. tabs).
