### ISSUE TITLE
Error while opening 2 jnlp files

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#109]
See the following screenshot:
![image](https://user-images.githubusercontent.com/26277832/50547668-c7bbf380-0c3e-11e9-8a68-995e335c1ab6.png)

I've never had this issue before, and I'm not sure if you would like to enable people to work on 2 jnlps (in this case I want to merge the content of one PW into another one).

**Comment by khanspers** [comment]
Hm, I often have multiple instances of PV open and never have a problem. I download each jnlp then launch by "open with > java web start". 
Launching multiple instances of plain PV and loading each pathway from plugin works too for me.

**Comment by DeniseSl22** [comment]
Mhh okay, if I find this behavior again, we can revisit. Closing this issue for now.
