### ISSUE TITLE
File not found exception

### ISSUE THREAD

**Issue by LaurenDupuis** [PathVisio/pathvisio#110]
Can not load files that have special characters in the path. Error message not clear.

**Comment by egonw** [comment]
Can you please add the filename?

**Comment by LaurenDupuis** [comment]
The problematic filename was stat_results_E-GEOD-29819.raw.1_2019-02-01_03-58_34_0(2). The error message was Error: Could not set dataset as current dataset in PathVisio. Please restart PathVisio and retry the data import. It was not clear to remove the parentheses (or special characters) from the file name with this error message.

**Comment by DeniseSl22** [comment]
@LaurenDupuis I think this is because of the (2) and other brackets. Please remove these from the file name, then it should work (Windows add this automatically if you have files with the same name).
