### ISSUE TITLE
Error log location

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#115]
For the Error log related to PV related problems, I'm not sure at what location I can find it (this is different from the data loading identifier mapping errors). Perhaps a hint where this file is located would help.

![image](https://user-images.githubusercontent.com/26277832/56123701-45e5a100-5f75-11e9-9b1f-05f9abb3c6a0.png)

**Comment by mkutmon** [comment]
can you send me the log file?

**Comment by DeniseSl22** [comment]
okay, so we should add a linkout to this FAQ ;)

**Comment by DeniseSl22** [comment]
This info has been added to the main website FAQ :)
