### ISSUE TITLE
Update website printscreens

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#148]
@mkutmon I've taken the liberty of changing some basics texts on the main website, however there are quite a lot of printscreens which are outdated. There is also a discrepancy between [explanation on WikiPathways](https://www.wikipathways.org/index.php/Help:Authors) (most made by @khanspers I believe) and what is offered on PV website; probably due to more details on WPs website on how to get PWs at required level for "Approved" tag. I think it would be good to have one source of information, and then point to that from other pages (to keep info consistent etc.).

Pages which need updating regarding the printscreens are:
- [ ] https://www.pathvisio.org/getting-started/
- [ ] https://www.pathvisio.org/documentation/tutorials/ (and child pages)
- [ ] https://www.pathvisio.org/documentation/ (and child pages)

**Comment by mkutmon** [comment]
New website should fix those issues.
