### ISSUE TITLE
Get rid of developers.pathvisio.org pages

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#149]
Some pages on the main website link out to very old/outdated developers.pathvisio.org pages: 
- [ ] http://developers.pathvisio.org/wiki/PathwayStyles
- [ ] http://developers.pathvisio.org/wiki/PluginDevelopment

We should see what info is on these old websites (last update 5 years ago, bug trackers are now on github etc.), add them to the new one, and then remove the last linkouts on the main page.
Is there anyone who still has access to the old developer pages? @mkutmon @AlexanderPico (there's also some info on WPs on this website)?

**Comment by AlexanderPico** [comment]
A Trac wiki... hmm... This could be hosted by Scooter at UCSF or perhaps by you guys? I'm not sure. 

In any case, I do have a login that works, so I can edit pages there. But I gather the request is to remove links from the main site and just turn off this site, right?

I'm confident that I don't need any of the pages "For WikiPathways Developers". These have all been replaced/updated with better links and content. @Tina and decide regarding the PathVisio dev links.

**Comment by mkutmon** [comment]
I think on the new website those links are gone.
