### ISSUE TITLE
error 404

### ISSUE THREAD

**Issue by ala351970** [PathVisio/pathvisio#152]
https://pathvisio.github.io/plugin/wikipathways-plugin/ for installing plugin, gives me error 404, file not found. any help or other way to install plugin in pathvisio 3.3?

**Comment by mkutmon** [comment]
At this moment, it is not possible to install the plugins from the repository. We are moving the repository to a new location so it will hopefully online again soon. For now, you can provide the needed jar files and install them locally (Plugins -> Install local plugins). 

For the WikiPathways app, you need to download the main jar file (org.pathvisio.wpclient.jar) and the dependencies.zip file from here: https://github.com/PathVisio/WP-plugin/releases. Make sure all jars are in the same directory, then install them locally. 
Let me know if you run into any problems.

The website is also still work in progress. It will take a little while until everything has been moved. I'm sorry for any inconvenience.

**Comment by ala351970** [comment]
Thanks for your help
I did install  MAPP builder and wikipathways plugins
is there any other plugins?

I couldn't get any database to install it, like gene database. so I
couldn't draw any pathway.
How to resolve these issues?
I will be waiting for your reply.

Kind regards



Contact Number 0027 745010061
Email address : ala3570@gmail.com

**Comment by mkutmon** [comment]
You can download the BridgeDb databases from here: https://bridgedb.github.io/mapping-databases/ensembl-gene-mappings.html. 
For drawing pathways, you don't need any other plugins.

**Comment by ala351970** [comment]
Thanks a millennium for your help Martina. I do appreciate it.

Please is any thing you can help me to improve my pathway drawing let me
know.

Thanks



Contact Number 0027 745010061
Email address : ala3570@gmail.com

**Comment by mkutmon** [comment]
I always advise to go through the Academy when getting started:

**Comment by ala351970** [comment]
Thanks



Contact Number 0027 745010061
Email address : ala3570@gmail.com
