### ISSUE TITLE
Trouble Downloading PathVisio

### ISSUE THREAD

**Issue by angelroyale** [PathVisio/pathvisio#153]
Upon opening the .jar version on my Mac, the program asked to download JDK to help run it. I followed the link and set the JDK program up but got this error message when I tried to open PathVisio:
<img width="1440" alt="Screen Shot 2020-03-06 at 2 53 31 AM" src="https://user-images.githubusercontent.com/61864792/76064071-f4f8e580-5f56-11ea-9e92-feb1cef2acaf.png">

**Comment by LMBraden** [comment]
I am having the same issues. Any suggestions to fix?

**Comment by mkutmon** [comment]
Did you install Java 8?
