### ISSUE TITLE
PathVisio failing to install on Mac

### ISSUE THREAD

**Issue by PranikaDC** [PathVisio/pathvisio#155]
Dear all,

I am facing a problem in installing the jar  file on my MacBook Pro. it gives an error as follows:
![y](https://user-images.githubusercontent.com/32042250/79468472-3f15c200-7fff-11ea-97d8-6092732cb8d2.png)

Can you please help me with this?
Thanks in advance!

**Comment by mkutmon** [comment]
Can you check which Java version you have?

**Comment by PranikaDC** [comment]
it is java version "14" 2020-03-17.

**Comment by mkutmon** [comment]
PathVisio currently only works with Java 8. We are working on upgrading the Java version but the current release still requires Java 8

**Comment by PranikaDC** [comment]
thanks for the information! Please update when you upgrade the java version as working with older versions of java is primarily not advised.

**Comment by oolonek** [comment]
Pasting here in case it can help someone.

Had Java 17 on macOS so pathvisio complained : 

```
➜  pathvisio-3.3.0 sh pathvisio.sh
Problem creating boot delegation class loader: java.lang.reflect.InaccessibleObjectException: Unable to make protected java.security.SecureClassLoader(java.lang.ClassLoader) accessible: module java.base does not "opens java.security" to unnamed module @49b70bc7
Installing bundles that are embedded in the jar.
Detected embedded bundle: org.apache.batik.svggen_1.7.0.v201011041433.jar
Loading jar:file:/Applications/pathvisio-3.3.0/pathvisio.jar!/org.apache.batik.svggen_1.7.0.v201011041433.jar
````
Followed these instructions https://medium.com/@brunofrascino/working-with-multiple-java-versions-in-macos-9a9c4f15615a to get jenv installed. Didn't know about this utility which conveniently helps to choose the java version you which to set for a given folder.

You might need to `echo eval "$(jenv init -)" >> /Users/username/.zshrc` at  one point if jenv complains. Alternatively run `jenv doctor` to be sure.

Then you can navigate to your pathvisio folder and run
`jenv local 1.8.0.292` (or the java8 version you have)

Like this you can have both java8 and more recent version cohabiting on your computer and linked to different folders.

**Comment by AlexanderPico** [comment]
Update on linked instructions at medium.com: 
 * Replace: `brew cask install java9`
 * With:  `brew install --cask homebrew/cask-versions/adoptopenjdk8`
