### ISSUE TITLE
Expression data

### ISSUE THREAD

**Issue by Alya-Nsc** [PathVisio/pathvisio#161]
Hello

I am learning to use Pathvisio. I have a problem to integrate the expression data to the pathway and there's no tutorial available. Could you please advise me on this?

Thank you
-Alya

**Comment by LaurenDupuis** [comment]
Hello Alya,

The tutorial available here <https://laurendupuis.github.io/Helis_Academy_April_2020/tutorials/Pathway_Analysis.html> can guide you through the process of importing expression data in PathVisio. If this does not help, can you provide more details on where the integration fails and the error message you receive?

Best,
Lauren

**Comment by Alya-Nsc** [comment]
Thank you for your prompt response. I will give it a try and let you know
how it goes.

Kind regards,
Alya

**Comment by Alya-Nsc** [comment]
Hi Lauren,

I still encountered problems when I tried to use EntrezID as the identifier
column although I have mapped it to EntrezGene as the system code
(DataImport5.png). I've also tried to use Ensembl ID and mapped it to
Ensembl Human (DataImport4.png). Both resulted in errors
(DataImport6.png):-

Line 2: L:"1" Error: Could not look up this identifier in the identifier
mapping database
Line 3: L:"503538" Error: Could not look up this identifier in the
identifier mapping database
Line 4: L:"29974" Error: Could not look up this identifier in the
identifier mapping database
Line 5: L:"2" Error: Could not look up this identifier in the identifier
mapping database
Line 6: L:"144571" Error: Could not look up this identifier in the
identifier mapping database

Have I chosen the wrong system code's database?

**Comment by LaurenDupuis** [comment]
Hi Alya,

For some reason I'm not able to see the images. Can you try attaching them again?


Best,
Lauren

**Comment by Alya-Nsc** [comment]
Hi Lauren,

Could you view it now?

**Comment by Alya-Nsc** [comment]
Hi Lauren, 

Sorry, I was replying from the email, thus included the pictures as attachments. Hope you could see it now.

![DataImport2](https://user-images.githubusercontent.com/69289558/89606516-c0d97600-d8a2-11ea-8822-8ff7fc235033.PNG)
![DataImport3](https://user-images.githubusercontent.com/69289558/89606518-c20aa300-d8a2-11ea-9e6d-a9ee94a82f06.PNG)
![DataImport4](https://user-images.githubusercontent.com/69289558/89606520-c2a33980-d8a2-11ea-97b9-fb9db02f51ca.PNG)
![DataImport5](https://user-images.githubusercontent.com/69289558/89606521-c33bd000-d8a2-11ea-9a84-a1c00a0caedd.PNG)
![DataImport6](https://user-images.githubusercontent.com/69289558/89606523-c33bd000-d8a2-11ea-8d84-8675984f4ede.PNG)
![DataImport1](https://user-images.githubusercontent.com/69289558/89606525-c3d46680-d8a2-11ea-9f72-47f2a57a270a.PNG)

**Comment by Alya-Nsc** [comment]
A side note, when I used the Ensembl ID as the primary identifier and set the Ensembl as the database, it worked with 1000+ genes unrecognised. Would this be recommended as my subjects are human so I thought it's best to use Ensembl human as database (but didn't recognise any genes)?

**Comment by LaurenDupuis** [comment]
Hi Alya,

Are your files tab delimited or comma delimited? We typically use tab delimited input files, so just make sure that your input file is indeed consistent with what you choose. As for the identifier, Ensembl human won't work unfortunately, so it's best just to use Ensembl because that database includes all of the human identifiers.

Does it work when you try that?

**Comment by Alya-Nsc** [comment]
Hi Lauren,

My fikes are in CSV format. I haven't tried using TXT for pathvisio but will give it a try :) 

I see -  thank you for explaining that to me. I will then be able to explain this in my write up. Yes, it does work when I use Ensembl.

Thanks a lot, Lauren for your help.

**Comment by Alya-Nsc** [comment]
Hi Lauren,

My files are in CSV format. I haven't tried using TXT for pathvisio but will give it a try :)

I see - thank you for explaining that to me. I will then be able to explain this in my write up. Yes, it does work when I use Ensembl.

Thanks a lot, Lauren for your help.

**Comment by Alya-Nsc** [comment]
I've tried using TXT files and it worked for all primary identifiers - Ensemble, Entrez and HGNC symbol. 

Thank you so much for your suggestions! Really appreciate it.

**Comment by LaurenDupuis** [comment]
No problem, and don't hesitate to contact us with any other questions!
