### ISSUE TITLE
file doesn't open

### ISSUE THREAD

**Issue by enila90** [PathVisio/pathvisio#172]
The pathvision.dat file doesn't open, so I can't run the program. I have tried to download it again and to open it as an administrator, but nothing happens after I try to launch it.

**Comment by mkutmon** [comment]
Can you please verify that you have Java 8 installed?

**Comment by mkutmon** [comment]
@enila90 were you able to solve the problem?

**Comment by enila90** [comment]
Yes, thank you!

Aline D. C. Brito
PhD student in Food technology
School of Food Engineering - University of Campinas

+55 19 996764160
aline.dc.brito@gmail.com
