### ISSUE TITLE
PathVisio is unable to connect to the online plugin repository

### ISSUE THREAD

**Issue by EnriqueSalasV** [PathVisio/pathvisio#173]
Hi 
I have tried to connect to the online plugin repository through the PathVisio Plugin Manager but it does not work. Is there an option to download and install the plugins?
I am following the WikiPathways tutorial and I need the BridgeDbConfig and WikiPathways plugins to advance.
Thanks!

Best 
Enrique Salas-Vidal

**Comment by mkutmon** [comment]
Let me quickly check. We had a server restart and I need to check if it's linked to that.

**Comment by mkutmon** [comment]
@EnriqueSalasV - the plugin repo should be accessible again. please let me know if you still have issues.
