### ISSUE TITLE
PathVisio does not connect to online plugin manager

### ISSUE THREAD

**Issue by fehrhart** [PathVisio/pathvisio#179]
See title - internet connection was not the problem, PV does not connect and you cant install plugins online.

**Comment by mkutmon** [comment]
Can you try the following: 
Edit > Preferences > Plugin Repository

Change URL to: https://repository.pathvisio.org/repository.xml

**Comment by mkutmon** [comment]
but currently it seems that it is an issue with the server

**Comment by fehrhart** [comment]
nope - was already set to this
Plugins - plugin manager - does now not even open a window

**Comment by mkutmon** [comment]
it works for me. and I now also checked with Luc and even with http it should work now.

**Comment by fehrhart** [comment]
tried again - now it works!

**Comment by fehrhart** [comment]
maybe restart bug... but I will forward the URL to Humera, she is also struglling with that

**Comment by mkutmon** [comment]
no changes should be required regarding the URL anymore.
