### ISSUE TITLE
Errors importing SBML and a SBGN Files

### ISSUE THREAD

**Issue by jordlang1992** [PathVisio/pathvisio#180]
Hello,

I downloaded Pathvisio a couple of weeks ago and am encountering a couple of errors. I know Pathvisio connects to the wikipathways database, but I want to import REACTOME and PANTHER pathways, if that's possible. For example, I exported a REACTOME pathway as SBGN and SBML files but received these errors:

#SBML error
Exception during conversation
See error log for details
class java.xml.stream.FactoryConfigurationError

#SBGN error
class java.lang.reflect.InvocationTargetException:null
See error log for details
class org.pathvisio.core.model.ConverterException

Thanks

**Comment by mkutmon** [comment]
Reactome pathways for human are converted to GPML format and can be browsed and downloaded in WikiPathways (https://www.wikipathways.org/index.php/Portal:Reactome). Panther pathways can currently not be opened in PathVisio.
