### ISSUE TITLE
Issues with installing Pathvisio

### ISSUE THREAD

**Issue by joanita03** [PathVisio/pathvisio#181]
When trying to download pathvisio I get the following error:
![image](https://user-images.githubusercontent.com/95219210/143855289-2e488d80-811b-41d7-b62a-32d7877ea176.png)

How do I solve this.
I am trying to download it on a windows OS and have Java 8 installed on my device.

**Comment by oolonek** [comment]
Maybe java8 is not the default version ? 
 
I solved this (on macOS) see https://github.com/PathVisio/pathvisio/issues/155#issuecomment-1059946761

Hope it works for you

**Comment by mkutmon** [comment]
did you check the FAQ for the installation (https://pathvisio.org/faq)? It shows how you can make sure the program runs with your installed Java 8 version.
