### ISSUE TITLE
Error while exporting pathway figure in .tiff format

### ISSUE THREAD

**Issue by Shubham-Specksy** [PathVisio/pathvisio#185]
Hello,
I am getting an error while exporting a pathway figure which I created in Pathvisio. I have also attached a screenshot for the same.

![Untitled](https://user-images.githubusercontent.com/110283833/181904185-3dc7d759-de42-4564-b6e3-9abc9beaaa48.png)

**Comment by mkutmon** [comment]
Thank you for your report. I will check what the issue could be. For now, I would advise exporting as SVG and then using Inkscape or a similar tool to convert to .tiff.

**Comment by Shubham-Specksy** [comment]
Yes, that works for me. Thank you.
