### ISSUE TITLE
Can't install on Win 11

### ISSUE THREAD

**Issue by shankar4** [PathVisio/pathvisio#187]
The problem seems similar to the one documented for Mac in the download instructions at: https://pathvisio.org/tutorials/installation_guide.html. However, details are different, as to be expected. I tried to follow this: https://support.microsoft.com/en-us/windows/a-driver-can-t-load-on-this-device-8eea34e5-ff4b-16ec-870d-61a4a43b3dd5. I restarted and tried to install, as suggested there. No luck. Please advise. Thanks

**Comment by mkutmon** [comment]
Please try one of the new installers. They should solve the installation issues.
