### ISSUE TITLE
Remove a literature reference

### ISSUE THREAD

**Issue by JonathanMELIUS** [PathVisio/pathvisio#19]
When a pathway element is deleted, also remove the literature reference link to the pathway element.

**Comment by JonathanMELIUS** [comment]
#20

**Comment by JonathanMELIUS** [comment]
Delete pathway element -> Ctrl-Z -> the gui doesn't display the reference. #20 

The reference is still save in the gpml after Ctrl-Z, and displayed if re-open.

**Comment by mkutmon** [comment]
Okay, I think for now we have an okay solution. There are still specific situations where the pubref is lost when using Ctrl-Z, but it's definitely better than what we have at the moment, so I will include the current solution in the release.
