### ISSUE TITLE
Citations - missing xref IDs

### ISSUE THREAD

**Issue by AlexanderPico** [PathVisio/pathvisio#190]
In a pathway edited in April 2022, this publicationXref was found:

> <bp:PublicationXref xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:id="b1f">
      <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string"/>
      <bp:DB rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PubMed</bp:DB>
      <bp:TITLE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Chapter 14: Pathways and functions of mammalian protein glycosylation</bp:TITLE>
      <bp:SOURCE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Gene Transfer and Expression in Mammalian Cells</bp:SOURCE>
      <bp:YEAR rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2003</bp:YEAR>
      <bp:AUTHORS rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Cumming DA</bp:AUTHORS>
    </bp:PublicationXref>

Notice the bp:ID line. This representation of "none" breaks libGPML, leading to an error about a missing citation xref.

I think either of these alternatives works fine with the current code:

> <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></bp:ID>

or 

> <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string">NA</bp:ID>

**Comment by larsgw** [comment]
> ```xml
> <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string"></bp:ID>
> ```

I think this only be achieved with `Format.setExpandEmptyElements(true)` which would apply to the entire GPML file.
