### ISSUE TITLE
Citations - duplicate fields

### ISSUE THREAD

**Issue by AlexanderPico** [PathVisio/pathvisio#191]
In a pathway edited in April 2022, each of the publicationXrefs contained duplicated fields (ID, DB, TITLE, SOURCE and YEAR) two more more times with a single element. Only the AUTHOR fields are unique. For example:

> <bp:PublicationXref xmlns:bp="http://www.biopax.org/release/biopax-level3.owl#" xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#" rdf:id="d4c">
      <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string">11278778</bp:ID>
      <bp:DB rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PubMed</bp:DB>
      <bp:TITLE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The yeast ALG11 gene specifies addition of the terminal alpha 1,2-Man to the Man5GlcNAc2-PP-dolichol N-glycosylation intermediate formed on the cytosolic side of the endoplasmic reticulum.</bp:TITLE>
      <bp:SOURCE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">J Biol Chem</bp:SOURCE>
      <bp:YEAR rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2001</bp:YEAR>
      <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string">11278778</bp:ID>
      <bp:DB rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PubMed</bp:DB>
      <bp:TITLE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The yeast ALG11 gene specifies addition of the terminal alpha 1,2-Man to the Man5GlcNAc2-PP-dolichol N-glycosylation intermediate formed on the cytosolic side of the endoplasmic reticulum.</bp:TITLE>
      <bp:SOURCE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">J Biol Chem</bp:SOURCE>
      <bp:YEAR rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2001</bp:YEAR>
      <bp:ID rdf:datatype="http://www.w3.org/2001/XMLSchema#string">11278778</bp:ID>
      <bp:DB rdf:datatype="http://www.w3.org/2001/XMLSchema#string">PubMed</bp:DB>
      <bp:TITLE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">The yeast ALG11 gene specifies addition of the terminal alpha 1,2-Man to the Man5GlcNAc2-PP-dolichol N-glycosylation intermediate formed on the cytosolic side of the endoplasmic reticulum.</bp:TITLE>
      <bp:SOURCE rdf:datatype="http://www.w3.org/2001/XMLSchema#string">J Biol Chem</bp:SOURCE>
      <bp:YEAR rdf:datatype="http://www.w3.org/2001/XMLSchema#string">2001</bp:YEAR>
      <bp:AUTHORS rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Cipollo JF</bp:AUTHORS>
      <bp:AUTHORS rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Trimble RB</bp:AUTHORS>
      <bp:AUTHORS rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Chi JH</bp:AUTHORS>
      <bp:AUTHORS rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Yan Q</bp:AUTHORS>
      <bp:AUTHORS rdf:datatype="http://www.w3.org/2001/XMLSchema#string">Dean N</bp:AUTHORS>
    </bp:PublicationXref>

This doesn't appear to break our current processing pipeline for md and tsv files, but it's probably something we should fix.

**Comment by larsgw** [comment]
Based on the git history this might have been the case for 10 years but when these properties are set they're technically just added, and the `maxCardinality` makes sure the old element is removed. Except, they're only removed from the internal representation of the data (line 65), not the `org.jdom2.Element` (line 70):

https://github.com/PathVisio/pathvisio/blob/33d315b4e0fab46768398773f28b87ad4a829187/modules/org.pathvisio.core/src/org/pathvisio/core/biopax/BiopaxNode.java#L61-L70

Fix should be as easy as calling `removeProperty()` instead of `properties.remove()` as it updates `wrapped`. I'm including a patch in an upcoming PR.

**Comment by larsgw** [comment]
(but to fix existing GPML, it also needs to delete all occurrences, not just the first.)
