### ISSUE TITLE
Update Templates in PV

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/pathvisio#3]
_Reported by AlexanderPico_ (http://developers.pathvisio.org/ticket/1824)

PV interaction templates should be updated:
- The reaction template should have a mim-conversion arrow between metabolites.
- And the other template (for undirected interactions?) should probably be removed.
- Maybe add templates for: 
 - molecule binding a receptor complex 
 - activating transcription 
 - phosphorylation

**Comment by JonathanMELIUS** [comment]
#6
