### ISSUE TITLE
Unsorted library (also ontology issue)

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#38]
1. The library is not sorted; found some problems in the WP academy regarding glucose-6-phosphate and glucose 6-phosphate (where one bar is missing). Think that the library where one searches for a compound, should be ordered in some way (preferably alphabetical). In this way, one can see if a compound exists more often, and which names are acceptable.​ (Perhaps the double names should be combined/deleted to overcome further annotation problems?)

**Comment by ariutta** [comment]
This refers to the results from "DataNode properties" > Annotation > Search.

How about sorting by relevance, maybe using [Levenshtein Distance](https://commons.apache.org/sandbox/commons-text/jacoco/org.apache.commons.text.similarity/LevenshteinDistance.java.html)?

**Comment by DeniseSl22** [comment]
Sounds like a good idea! 

However, this does not resolve the "double"/differently typed names right? Perhaps this should be done manually --> upon finding double names, check if these have been used in any existing pathways (with a SPARQL-query) and changing them to one and the same; after which the less favourable double name can be deleted from the library. This will clean up the library as well, making it more user friendly.

**Comment by mkutmon** [comment]
Do you mean here the searching of an element name in PathVisio? 
PathVisio uses the default search implemented in BridgeDb. We could implement a different sorting algorithm for PathVisio but I think this is a general BridgeDb problem, so maybe we should report it there. @egonw what do you think?

**Comment by DeniseSl22** [comment]
Searching of a compound name (which is not the same as an element ;)....)
And yes, I mean the library in Pathvisio. It popped up when I used the WPs academy.

**Comment by mkutmon** [comment]
Well it's the search field that then searches a bridgedb database (independent of which pathway element type you search for - only the database is different) - if you create a metabolite it's the metabolite database, if it's a gene it's the gene database. 
but still it's bridgedb code that's used to search and the sorting is also done by bridgedb, I think. @JonathanMELIUS do you know how the results are ranked?

**Comment by JonathanMELIUS** [comment]
The results are sorted in PathVisio code here:
https://github.com/PathVisio/pathvisio/blob/1a0853d7c9c363008b782399a1b0b30588a836db/modules/org.pathvisio.gui/src/org/pathvisio/gui/dialogs/DatabaseSearchDialog.java#L47

So it means that currently the results are ranked by ids.

But we can just enable the JTable to be sortable, with:
`table.setAutoCreateRowSorter(true);`
https://github.com/PathVisio/pathvisio/blob/1a0853d7c9c363008b782399a1b0b30588a836db/modules/org.pathvisio.gui/src/org/pathvisio/gui/dialogs/DatabaseSearchDialog.java#L68

Then the user is free to sort the way he wants.

![sortable_search](https://user-images.githubusercontent.com/6931588/27432908-8fdcc270-5752-11e7-9d16-b0bbcaf88e26.png)

**Comment by DeniseSl22** [comment]
Thank you Jonathan, it would be nice if we could include this new feature in a new release of Pathvisio.
I hope we can also include a sorting mode for the statistics part; when doing metabolomics research, the data is much more sparse then from array analysis. So I would like to use the statistical part, to find which PWs have measured metabolites in them, instead of looking at the Z-score to find which PWs are significantly altered. For example, see Figure below:
The PW with the most measured metabolites (highlighted in blue) has a very low Z-score)

![image](https://user-images.githubusercontent.com/26277832/28623828-68dbc09c-7217-11e7-9332-79ad53fcbc7a.png)

**Comment by mkutmon** [comment]
@JonathanMELIUS did you commit the fix for this? I don't see any commits linked to this issue.

**Comment by DeniseSl22** [comment]
Jonathan showed me on his computer that he managed the sorting; don't know if he pushed the change yet...

**Comment by mkutmon** [comment]
fixed 618f571
