### ISSUE TITLE
Library position on screen

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#39]
2. The library opens up very low on the screen, in order to accept a found compound name+info, one has to scroll down all the time.

**Comment by ariutta** [comment]
Could you provide a screenshot of this? I think you're referring to the search results from BridgeDb?

**Comment by DeniseSl22** [comment]
![image](https://cloud.githubusercontent.com/assets/26277832/24545905/6d282786-1609-11e7-9648-30352ef54e45.png)

**Comment by DeniseSl22** [comment]
Perhaps this only occurs when a compound (or part of the search name) occurs in a vast amount in the library...

**Comment by mkutmon** [comment]
@DeniseSl22 location of search result is now based on the data node dlg from which the search is started. this should make the position easier. I want to release PV on Monday, can you test this before then?

**Comment by mkutmon** [comment]
https://github.com/PathVisio/pathvisio/commit/1e4b515fc2c9594187d0f3393461a6894e9de7ef

**Comment by DeniseSl22** [comment]
Seems to be fixed, so closing this issue ;)
