### ISSUE TITLE
Extra message about updating quality tags when doing update to WP in JNLP

### ISSUE THREAD

**Issue by khanspers** [PathVisio/pathvisio#41]
When editing a pathway from WP by launching the JNLP from WP, I got a new message when doing "Update". See attached. The message is in addition to the actual message where the user can select to update quality (curation) tags. Is this a bug? 
![screen shot 2017-04-24 at 11 10 43 am](https://cloud.githubusercontent.com/assets/1442197/25360884/fe8603d4-28ff-11e7-87a2-d34f1a92ff9c.png)

**Comment by mkutmon** [comment]
@khanspers can you please move this issue to the WP plugin repo? https://github.com/PathVisio/WP-plugin/issues
