### ISSUE TITLE
Nicer visualisation of dataset with multiple visualisation needs.

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#44]
For the current dataset we are working on, we want to visualise multiple items in Pathvisio:
1. %occurrence in sick group
2. %occurrence in healthy group
3. Up/down regulated metabolite
4. significance

See image below:

![image](https://user-images.githubusercontent.com/26277832/27587883-6d4cf0d4-5b46-11e7-861c-77c1bf1c328e.png)

However, the visualisation of point 1 and 2 are hard to separate from each other. Is it perhaps possible to do something like this (sorry for the self made paint image):

![image](https://user-images.githubusercontent.com/26277832/27587972-c6da81de-5b46-11e7-85b8-6317081a78b8.png)

This means extending the node (if there is data for it), to visualise the dataset below the node name, and perhaps with lines between the different visualisation options.

**Comment by mkutmon** [comment]
Something like that is not currently possible in PathVisio. I would advise to work with different colors. That should make the visualization a lot more intuitive and separate the different sections. I'll try to create an example tomorrow.

**Comment by DeniseSl22** [comment]
Yes I know it is currently not possible, however could this perhaps be added in the future?

**Comment by DeniseSl22** [comment]
Mhh okay; too bad!
