### ISSUE TITLE
Library and secondary IDs

### ISSUE THREAD

**Issue by DeniseSl22** [PathVisio/pathvisio#48]
Hi all, (again about the library, sorry about that ;)....)

In the Pathvisio library, secondary identifiers of ChEBI are included as well (Marvin found this for bicarbonate). I think for a new Pathvisio release, we should remove these secondary IDs as a option; and replace all secondary ChEBIs with primary in WPs. Since the secondary IDs are not mapped via bridgeDB.

@marvinm2 
@egonw 
@mkutmon

**Comment by DeniseSl22** [comment]
After consulting with Jonathan, he told me that the library(search function in Pathvisio) uses the content of BridgeDB databases.
So, if any secondary metabolites IDs are being found in the "library", it is because they are in the metabolites bridgeDB file. We do not need a new Pv release for this change.

Is this something we want to include in the bridge file (I have other examples, where I could not create a mapping, because the secondary ID was used in a dataset....)? 
Or do we just want the primary ones included, and another way to map the secondary to the primary IDs?

**Comment by mkutmon** [comment]
@DeniseSl22  did you move this issue to the bridgedb repo? then I close it here.

**Comment by DeniseSl22** [comment]
Nope not yet; I will do it right away :)
But it is a problem which we do not have the solution for right now (according to Chris and Egon)...

**Comment by DeniseSl22** [comment]
Moved to https://github.com/bridgedb/BridgeDb/issues/55
