### ISSUE TITLE
Open specific pathway from WikiPathways when starting PV

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/pathvisio#5]
To provide PathVisio directly from a pathway page on WikiPathways, the application should allow the WikiPathways identifier as a command line argument. If the WP plugin is loaded, the argument will be read by the plugin and the pathway will be automatically opened. 

_3 things are necessary_:
1. Adapt PV to allow a command line argument (-wp) 
2. Adapt WP plugin so it reads the provided argument and opens the pathway if it is not null
3. JNLP file needs to be generated on the specific pathway page with the correct attribute.

**Comment by mkutmon** [comment]
PV core part (1) is done: b51a939

**Comment by mkutmon** [comment]
WP plugin part (2) has been fixed - everything should be working after plugin release
https://github.com/PathVisio/WP-plugin/commit/14626215c16521d5ef7eea88507d01bb62b4cd8d

**Comment by mkutmon** [comment]
WP JNLP part (3) needs to be resolved. JNLP file needs to be generated on demand by adding:
```
<application-desc main-class="org.pathvisio.launcher.PathVisioMain">
    <argument>-wp</argument>
    <argument>WP4</argument>
</application-desc>
```
instead of 
`<application-desc main-class="org.pathvisio.launcher.PathVisioMain"/>`

**Comment by ariutta** [comment]
For WP JNLP part (3), it sounds as if we might have two options:

We create a directory of JNLP files, one for each pathway. Then JavaScript in the page generated by [PathwayView.php](http://svn.bigcat.unimaas.nl/wikipathways/trunk/wpi/extensions/PathwayViewer/PathwayViewer.php) calls `deployJava.createWebStartLaunchButton('http://wikipathways.org/pathways/jnlp/WP4.jnlp', '1.7.0');`.

or

We create a MediaWiki extension (PHP file) that can generate a JNLP file for a specific pathway based on query parameters. JavaScript in the page generated by [PathwayView.php](http://svn.bigcat.unimaas.nl/wikipathways/trunk/wpi/extensions/PathwayViewer/PathwayViewer.php) calls `deployJava.createWebStartLaunchButton('http://wikipathways.org/index.php/JNLP?id=WP4', '1.7.0');`.

Do either of these sound right? I don't know about any security vulnerabilities that could be caused by the second option.

**Comment by ariutta** [comment]
I'm referencing this page on [Deploying a Java Web Start Application](https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html)

**Comment by ariutta** [comment]
Do we need to be specific to pathway version?

**Comment by ariutta** [comment]
OK, here's a start for your review:

The files are on the pvjs.wikipathways.org test server in the /var/www/pvjs.wikipathways.org/wpi/extensions/PathwayViewer directory.

* PathwayViewer.php calls two JavaScript files: https://www.java.com/js/deployJava.js and pathwayviewerJavaWebStartLauncher.js
* pathwayviewerJavaWebStartLauncher.js calls `deployJava.createWebStartLaunchButton` with a query parameter for pathwayviewerJNLPGenerator.php
* [pathwayviewerJNLPGenerator.php](
http://pvjs.wikipathways.org/wpi/extensions/PathwayViewer/pathwayviewerJNLPGenerator.php?identifier=WP1) is a PHP file that generates the required JNLP file based on pathwayviewerJNLPTemplate.xml and the query parameter passed in.

**Comment by ariutta** [comment]
pathwayviewerJavaWebStartLauncher.js will reference a url of this format:

http://wikipathways.org/index.php/pathwayviewerJNLPGenerator?identifier=WP2516&version=84490

(Or if at pvjs.wikipathways.org, it will use the pvjs subdomain.)

We need to do due diligence for security for this set up. I don't know enough about MediaWiki and Java/JNLP to take that on.

I remember is that Mark or one of the other people at a MediaWiki conference said it's safer to make pages available via the extension mechanism (e.g., it is actually not ideal that we make PathwayWidget.php available via http://www.wikipathways.org/wpi/PathwayWidget.php). But I don't know how to make pathwayviewerJNLPGenerator.php available at http://wikipathways.org/index.php/pathwayviewerJNLPGenerator

**Comment by AlexanderPico** [comment]
After reviewing the above, it looks like we have just a few more steps before we can test...
1. We need a test server!
2. We are not sure about the syntax that seems to specify a Java version. See pathwayviewerJavaWebStartLauncher.js and these docs: https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html

Tina, Nuno: do we have  a test server?  The test server plan is here: https://docs.google.com/document/d/1qyzfPrn1mw0Q5Iib9kRwEsGyUm-mxHkk59cZ1lnsfHs/edit
We should have trunk.wikipathways.org up with the trunk code to dev things like this, right?

Tina, Nuno: do you have experience with webstart jnlp syntax and how/if Java version needs to be specified.

**Comment by mkutmon** [comment]
I think, I wasn't clear enough. We need to extend the current pathvisio.jnlp file (http://www.pathvisio.org/data/releases/current/webstart/pathvisio.jnlp) with the the extended application-desc argument. Everything else needs to be the same as the PV webstart file. So I guess the php file should get the current jnlp file from pathvisio.org and extend the application-desc tag with the pathway id + revision. 
`<?xml version="1.0" encoding="UTF-8"?>
<jnlp codebase="http://www.pathvisio.org/data/releases/current/webstart/" href="pathvisio.jnlp">
	<information>
		 <title>PathVisio</title>
		 <vendor>BiGCaT Bioinformatics, Maastricht University</vendor>
		 <icon href="bigcateye.gif"/>
		 <offline-allowed/>
		<shortcut>
			<desktop/>
			<menu submenu="PathVisio 3.2.2"/>
		</shortcut>
	</information>
	<resources>
		 <j2se version="1.6+" java-vm-args="-Xmx512M"/>
		 <jar href="pathvisio.jar"/>
	</resources>
	<application-desc main-class="org.pathvisio.launcher.PathVisioMain"/>
	<security>
		 <all-permissions/>
	</security>
</jnlp>`

**Comment by ariutta** [comment]
In our JS, do we need to change this line from the [example](https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html):

```JavaScript
deployJava.createWebStartLaunchButton(url, '1.7.0');
```

to this?

```JavaScript
deployJava.createWebStartLaunchButton(url, '1.6.0');
```

**Comment by ariutta** [comment]
For WP4, would this be the desired JNLP file?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<jnlp codebase="http://www.pathvisio.org/data/releases/current/webstart/" href="pathvisio.jnlp">
    <information>
         <title>PathVisio</title>
         <vendor>BiGCaT Bioinformatics, Maastricht University</vendor>
         <icon href="bigcateye.gif"/>
         <offline-allowed/>
        <shortcut>
            <desktop/>
            <menu submenu="PathVisio 3.2.2"/>
        </shortcut>
    </information>
    <resources>
         <j2se version="1.6+" java-vm-args="-Xmx512M"/>
         <jar href="pathvisio.jar"/>
    </resources>
    <application-desc main-class="org.pathvisio.launcher.PathVisioMain">
        <argument>-wp</argument>
        <argument>WP4</argument>
        <argument>88153</argument>
    </<application-desc>
    <security>
         <all-permissions/>
    </security>
</jnlp>
```

**Comment by mkutmon** [comment]
Currently we support 1.6+, so I guess 
`deployJava.createWebStartLaunchButton(url, '1.6.0');`
would be correct.

About the JNLP file - looks good - the JNLP file will be updated with every PV release so it would be ideal if the script could get the current JNLP file and adapt that one, so we don't need to adapt WP code for each PV release. I haven't implemented the revision attribute yet, but I assume, we would need something like this:
`<application-desc main-class="org.pathvisio.launcher.PathVisioMain">
        <argument>-wp</argument>
        <argument>WP4</argument>
        <argument>-wprev</argument>
        <argument>88153</argument>
    </<application-desc>`

**Comment by ariutta** [comment]
OK, once I have a working test server, I'll update pathwayviewerJNLPGenerator.php to look like this:

```php
<?php
/**
 * Generate the JNLP file required to open the pathway
 * specified by the identifier query parameter
 *
 * Reference page:
 * https://docs.oracle.com/javase/tutorial/deployment/webstart/deploying.html
 * Github issue:
 * https://github.com/PathVisio/pathvisio/issues/5
 */

  header('Content-Type: text/xml');
  ini_set("error_reporting", 0);

  if (isset($_GET['identifier'])) {
    $identifier = htmlspecialchars($_GET['identifier']);
  }
  else {
    $identifier = 'WP4';
  }

  // see http://schema.org/version
  if (isset($_GET['version'])) {
    $version = htmlspecialchars($_GET['version']);
  }
  else {
    $version = 0;
  }

  // XML JNLP
  //$template_path = './pathwayviewerJNLPTemplate.xml';
  $template_path = 'http://www.pathvisio.org/data/releases/current/webstart/pathvisio.jnlp';
  $jnlp = simplexml_load_file($template_path);
  $application_desc_el = $jnlp->application-desc[0];
  $application_desc_el->argument[0] = '-wp';
  $application_desc_el->argument[1] = $identifier;
  $application_desc_el->argument[2] = '-wprev';
  $application_desc_el->argument[3] = $version;
  echo $jnlp->asXML();
?>
```

**Comment by ariutta** [comment]
@mkutmon, the pathwayviewerJNLPGenerator.php file now pulls from the template you specified and inserts the four `argument` elements. You can view an example here:
http://pvjs.wikipathways.org/wpi/extensions/PathwayViewer/pathwayviewerJNLPGenerator.php?identifier=WP4&version=88153

pathwayviewerJavaWebStartLauncher.js updated to specify `1.6.0`.

### Remaining Issues

http://pvjs.wikipathways.org is not working correctly. It does not let you visit the normal home page or pathway pages. @nunogit, do you know what's wrong with it?

@mkutmon, this is about as far as my knowledge goes in JNLP and MediaWiki. I'll hand off the final integration to you.

**Comment by mkutmon** [comment]
Update:
- [x] PV can be started with -wpid argument (revision is not needed - older revisions can not be updated - so always the latest version of the pathway will be loaded)
- [x] If needed PV installs WikiPathways plugin on startup

Now I need to finalize the WP plugin with this feature and release it.
