### ISSUE TITLE
introduce mim:translocation

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#56]
As outlined in the paper [0]:

![image](https://user-images.githubusercontent.com/26721/31249455-a93cd224-aa17-11e7-8730-5052b075d833.png)

The patch can reuse the icon, so even I should be able to create that...

0.https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1345641/

**Comment by DeniseSl22** [comment]
Done, see: https://github.com/PathVisio/pathvisio/commit/ff255f61bbe97f7b13e1c854e9b00b42653768b4

**Comment by egonw** [comment]
Is there an example pathway with an example already? Then I can start on the needed checking and updates of the WPRDF.
