### ISSUE TITLE
Uploading Illumina data set

### ISSUE THREAD

**Issue by Doncheff** [PathVisio/pathvisio#60]
Dears,

Probably I am writing about something that has been discussed in the past. I have checked all of the relevant topics but could not find any useful information that might help me solving the issue I am facing at the moment.

I am trying to analyse data obtain from Illumina microarray beatchip. The accessions are annotated with ILMN_ prefix for each gene with additional numeric code (proprietary annotation) which unfortunately are not recognized by PathVisio when I am trying to import the file. I am getting a message that all of lines are unrecognized (ecceptions - while reading the data). 
The gene list is Hs_Derby_Ensemble downloaded from the PathVisio homepage. I am using System Code Il - relevent to the Illumina chip. The rest of the columns are A, B and Fold change.
Does anyone have any idea, why I cannot import my data successfully?

Thank you for your help in advance.

**Comment by mkutmon** [comment]
Identifiers are only recognized when they are in the identifier mapping database. Can you provide a couple of example identifiers?

**Comment by Doncheff** [comment]
Dear Tina,

Thank you for your swift reply. 

The Illumina`s microarray annotation could be found on the following link:

https://support.illumina.com/array/array_kits/humanht-12_v4_expression_beadchip_kit/downloads.html

I am also uploading a sample file from my data.

I hope you find this information useful for you.


Kind regards,

Petar

**Comment by Doncheff** [comment]
Dear Tina,

For some reason I was not able to upload my example data in Github so I am
sending it via e-mail.

Regards,

Petar

2017-12-05 16:20 GMT+02:00 Martina Summer-Kutmon <notifications@github.com>:

**Comment by Doncheff** [comment]
Dear Tina,

I have found out that after saving the file in text (tab delimeted) file I still have to upload it using the comma as separator. In tutorial 2 the example file should be uploaded using 'tab" separator. In this regard I think the culprit might be in some hidden characters within the excel file. Have you any idea how can I make a clean text (tab delimited) file for PathVisio.

Thank you in advance.

Kind regards,

Petar

**Comment by mkutmon** [comment]
I haven't received the example data file. If you could send me the file then I can check how to import it. You can import comma-separated files - just select comma as the separator in the import dialog. Also check in the preview if the data looks like you would expect!

**Comment by Doncheff** [comment]
Dear Tina,

Thank you for your e-mail.

I am importing the document using the "comma" separator and the data does
really looks as it is in the xls, cvs, text (tab delimeted) file.
Unfortunately whne I click 'Next' I see that all of the entries are
parcelled as 'ecceptions' and at the end I have all of the lines as
unrecognized. I assume the culprit might be some hidden characters within
the data file (such as commas) which are blocking the software from
obtaining the right identifier.

I am attaching the example sheet one more time. Please, let me know if you
can open it.

Thank you for you support.

Kind regards,

Petar

2017-12-07 10:31 GMT+02:00 Martina Summer-Kutmon <notifications@github.com>:

**Comment by mkutmon** [comment]
I checked the annotation file now and verified that as an example for gene "ST8SIA3" (Entrez Gene identifier: 51046), there are the correct Illumina identifiers in the mapping database (ILMN_1855910) which means they should be recognized. The file attachment on github doesn't seem to work. Can you send me the example file to my email directly?

**Comment by mkutmon** [comment]
See solution: https://groups.google.com/forum/#!topic/wikipathways-discuss/HZo62y10SUw
