### ISSUE TITLE
quering PubMed IDs and ontologies not possible

### ISSUE THREAD

**Issue by fehrhart** [PathVisio/pathvisio#63]
...at least not for me today.
Anyone else experienced the same problem?

**Comment by mkutmon** [comment]
@fehrhart Pubmed Query from within PathVisio works for me. Can you give me the pubmed id that you are trying to annotate?

**Comment by fehrhart** [comment]
Sure, all the PMIDs which are in the pathway I am currently working at: WP4222
27037577
18474859
4331040
9416770

**Comment by mkutmon** [comment]
@fehrhart hmm... pubmed query for all those identifiers works fine more. What kind of error do you get?

**Comment by fehrhart** [comment]
When I hit the "query Pubmed" button the quering window opens and does not
close again finishing the task but endless quering.

**Comment by mkutmon** [comment]
I assume you tried to restart pathvisio?

**Comment by fehrhart** [comment]
From 2 different days in two different networks :)
(same computer)

**Comment by mkutmon** [comment]
could the problem be the internet connection? since the pubmed query is actually querying the online API to retrieve the information? 
do you see any errors thrown in the PathVisio.log file (in your home directory, go into the hidden directory “AppData”- “Roaming” – “PathVisio”).
