### ISSUE TITLE
Hrefs in labels pathvisio

### ISSUE THREAD

**Issue by marvinm2** [PathVisio/pathvisio#65]
I heard that it was possible to put a direct link in a label in PathVisio. How do we do that? According to @DeniseSl22 , this was mentioned during the last WP TC. This would be very useful for linking to diseases (Denise) and Key Events (for me).

**Comment by mkutmon** [comment]
Okay, I found this commit: http://developers.pathvisio.org/attachment/ticket/1146/bug1146_branch.txt 
I think you should be able to add a href in the properties pane on the right side. Is that true?

**Comment by mkutmon** [comment]
tested with @DeniseSl22 - works but it would be nice to have a user-friendly right-click option to add/edit a hyperlink

**Comment by ariutta** [comment]
For pvjs, should these hrefs be actual links? My worry is that we could get spam links in WikiPathways.

**Comment by mkutmon** [comment]
we had this feature for a long time. i think it would be good to also support this in pvjs. we didn't have spam links until now, so i don't think we should worry too much - i think @egonw has a jenkins job running to check for new URLs, right (if not, that should be easy to implement, right?).
