### ISSUE TITLE
Design new basic interaction palette for PathVisio

### ISSUE THREAD

**Issue by mkutmon** [PathVisio/pathvisio#73]
remove arrow and tbar without semantic meaning and implement new basic interaction palette based on existing standards (MIM/SBGN/etc) for simple applications. Based on work by Anwesha.

1. develop proposal for palette to be presented and discussed in conference call

**Comment by DeniseSl22** [comment]
Check [this](https://docs.google.com/document/d/1YhaqPVznPyn270skwmEcDBWzezsu1lOClEG4eIKyTQM/edit?usp=sharing) googledoc for the planning + description of 8 suggested interactions.
Check [this](https://docs.google.com/spreadsheets/d/1_4eUvbYdGWSvtv8qP2gA45GKQUWrg8EuBvnSgO21MfM/edit?usp=sharing) spreadsheet for the overview of the mapping (previous work of Anwesha).

**Comment by DeniseSl22** [comment]
And update documentation [here](https://vm1.wikipathways.org/Help:Guidelines_EditorPalette) and update the WPs academy when palette is done.

**Comment by DeniseSl22** [comment]
Fixed with https://github.com/PathVisio/pathvisio/pull/121
