### ISSUE TITLE
metabolite identifiers should be sorted by closest match

### ISSUE THREAD

**Issue by egonw** [PathVisio/pathvisio#89]
Allowing in the following screenshot the exact match to show up at the top:

![image](https://cloud.githubusercontent.com/assets/26721/21256844/fd8ed8b6-c374-11e6-9deb-9444ac5b97ff.png)

**Comment by ariutta** [comment]
You could use Levenshtein distance.

**Comment by DeniseSl22** [comment]
I'll try to implement this, searching for chemical compounds by name is horrible right now.

**Comment by DeniseSl22** [comment]
Closing, moved to [BridgeDb issue tracker](https://github.com/bridgedb/BridgeDb/issues/97).
