### ISSUE TITLE
revision/build of "null"?

### ISSUE THREAD

**Issue by ariutta** [PathVisio/pathvisio#98]
I built PathVisio. But when I run `pathvisio -v`, I'm getting "PathVisio v3.3.0, build null". It looks as if the `build` info is `pathvisio.revision`, which I think is coming from [here](https://github.com/PathVisio/pathvisio/blob/61f15de96b676ee581858f0485f9c6d8f61a3476/modules/org.pathvisio.core/src/org/pathvisio/core/Engine.java#L542).

What needs to change to not have build be `null`?

**Comment by DeniseSl22** [comment]
Let's try to fix that for a new version of PV

**Comment by mkutmon** [comment]
this is from the old SVN revision. I will remove this from the -v version and if possible from the code.
